apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeus-service-account
  namespace: ac-agentic
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.zeus: >
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"zeus-frontend"}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeus-oauth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: zeus-service-account
  namespace: ac-agentic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zeus-view
  namespace: ac-agentic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: zeus-service-account
  namespace: ac-agentic
