# ArgoCD installation for ac-agentic namespace
# Using standard ArgoCD installation manifests

apiVersion: v1
kind: Namespace
metadata:
  name: ac-agentic
  labels:
    name: ac-agentic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: ac-agentic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-ac-agentic
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-ac-agentic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-ac-agentic
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: ac-agentic
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: ac-agentic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-server-ac-agentic
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-server-ac-agentic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-server-ac-agentic
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: ac-agentic